### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/temp-write#10]
~~Does this work on Windows?~~ This does work on Windows. You're not using a Windows-based CI ([AppVeyor](https://appveyor.com)) for anyone to see if tests pass.

**Comment by sindresorhus** [comment]
AppVeyor is too annoying to setup and maintain so I only do it on larger projects.

> This does work on Windows.

How does it not work?

**Comment by stevenvachon** [comment]
Sorry, late night. It *does* work. Edited original comment.

**Comment by stevenvachon** [comment]
AppVeyor has been painless for me the past year and a half.

**Comment by sindresorhus** [comment]
I'm just not interested in adding more boilerplate and churn.

**Comment by stevenvachon** [comment]
It's your project, but you may never know if something breaks on Windows.
