### ISSUE TITLE
Error ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by 1Map** [sindresorhus/temp-write#14]
I get the following error:

`Uncaught Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\MyApp\node_modules\temp-write\index.js`

I Use Latest NodeJS: 16.2.0
I Use Latest temp-write: 5.0.0

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by 1Map** [comment]
The problem is:
I had it like:

`tmpWrite = require('temp-write')`

and changed it to:

`import tmpWrite from 'temp-write'`

It then gives this error:

`'import ... =' can only be used in TypeScript files.ts(8002)`
