### ISSUE TITLE
On macOS, os.tmpdir() isn't the real path

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/temp-write#8]
```
❯ node --version
v7.4.0
❯ node -pe 'os.tmpdir()'
/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T
❯ node -pe 'fs.realpathSync(os.tmpdir())'
/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T
```

When writing a Node.js module using `temp-write`, `__filename` inside that module is different than the file path that is returned by `temp-write`.

Using macOS Sierra 10.12.3.

**Comment by sindresorhus** [comment]
Shouldn't `os.tmpdir()` return the actual path? Weird that it doesn't follow the symlink. That's very surprising. I can do that here, but would you mind opening an issue on Node.js if you agree?

**Comment by novemberborn** [comment]
> I can do that here, but would you mind opening an issue on Node.js if you agree?

Done: https://github.com/nodejs/node/issues/11422
